apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wvuzommrw-python
  janus-idp.io/tekton: wvuzommrw-python
  backstage.io/kubernetes-id: wvuzommrw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wvuzommrw-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
